### ISSUE TITLE
Twitter plugin error

### ISSUE THREAD

**Issue by fabiand93** [jkakavas/creepy#19]
I press the auto config helper and It sends me back to the menu screen

here is my log activity

main log

DEBUG:2015-10-01 07:37:50,863 In flickr.py:34: Trying to load the labels file for the flickr plugin .
DEBUG:2015-10-01 07:37:50,962 In googleplus.py:37: Trying to load the labels file for the googleplus plugin .
DEBUG:2015-10-01 07:37:50,971 In instagram.py:32: Trying to load the labels file for the instagram plugin .
DEBUG:2015-10-01 07:37:50,982 In twitter.py:36: Trying to load the labels file for the twitter plugin .
ERROR:2015-10-01 07:37:54,817 In twitter.py:132: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
File "/Applications/cree.py.app/Contents/Resources/plugins/twitter/twitter.py", line 88, in runConfigWizard
File "tweepy/auth.pyc", line 85, in get_authorization_url
File "tweepy/auth.pyc", line 68, in _get_request_token
TweepError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
DEBUG:2015-10-01 07:37:54,832 In flickr.py:34: Trying to load the labels file for the flickr plugin .
DEBUG:2015-10-01 07:37:54,835 In googleplus.py:37: Trying to load the labels file for the googleplus plugin .
DEBUG:2015-10-01 07:37:54,838 In instagram.py:32: Trying to load the labels file for the instagram plugin .
DEBUG:2015-10-01 07:37:54,843 In twitter.py:36: Trying to load the labels file for the twitter plugin .

**Comment by andypiper** [comment]
This is most likely an issue with SSL - Twitter dropped support for everything other than TLS last year https://twittercommunity.com/t/twitter-no-longer-supports-sslv3/25557

**Comment by andypiper** [comment]
Duplicate of #17 and #18

**Comment by jkakavas** [comment]
v1.4 comes out any time now ( struggling with the windows binaries) and I
have not been able to reproduce it there. Please be a little patient so
that we can see if the new tweepy version (3.4.0) fixed this

**Comment by andypiper** [comment]
Cool! :+1:

**Comment by jkakavas** [comment]
This should be solved with 1.4.1 , fell free to reopen it if that's not the case.

**Comment by bararchy** [comment]
@jkakavas Seems that the SSL Issue is still there

OS: Arch Linux
Kernel: 4.2.5-1-ARCH
Python: Python 2.7.10
Creepy: Up To Date 1.4.1

Log:

```
ERROR:2015-11-23 15:31:00,663  In twitter.py:194: Error authenticating with Twitter API.
ERROR:2015-11-23 15:31:00,665  In twitter.py:195: Unable to get username, invalid oauth token!
ERROR:2015-11-23 15:31:03,262  In twitter.py:194: Error authenticating with Twitter API.
ERROR:2015-11-23 15:31:03,264  In twitter.py:195: Unable to get username, invalid oauth token!
ERROR:2015-11-23 15:31:12,990  In twitter.py:194: Error authenticating with Twitter API.
ERROR:2015-11-23 15:31:12,991  In twitter.py:195: Unable to get username, invalid oauth token!
ERROR:2015-11-23 15:31:17,442  In twitter.py:383: [{'message': 'SSL is required', 'code': 92}]
```

**Comment by jkakavas** [comment]
Thats a different error than the OP had. I pretty sure that you have a rather old version of tweepy (http://www.tweepy.org/) installed in your system. 

Do you have this https://aur.archlinux.org/packages/python2-tweepy ? It should have brought tweepy 3.5.0 . If not please get pyhton-pip and bring tweepy latest version from there with
 
```
pip install -U tweepy
```

**Comment by bararchy** [comment]
@jkakavas If it's not the same issue then close this one, I'll open a new one. 
tweepy in latest version now, still error.

**Comment by jkakavas** [comment]
I'm sorry I offended your Github flow principles by answering to this thread while I should have replied "Open a new ticket".  Let's do that now ! :) And please offer something more concrete than "still error".
